services:
  console:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    working_dir: /app
    container_name: "az204-microsoft-graph-console"
    volumes:
      - .:/app
    tty: true